### ISSUE TITLE
The bloom's direction can be changed?

### ISSUE THREAD

**Issue by ChenZhongPu** [Tangdixi/DCPathButton#15]
By default, the **bloom**'s direction is at the top of the button. What if i want to let the **bloom** at other direction of the button? thanks.

**Comment by Tangdixi** [comment]
Nope, but I think we can add this feature in next version :)

**Comment by wangweiarr** [comment]
这个做的还是非常不错的,对分享精神表示感谢. 不过提个建议,既然都加到pods上来了,为何不提高一下可制订性呢?比如中心按钮的旋转可控,声音或者是展开方向和展开半径还有扇区角度..  虽然有点麻烦,但还是希望能有这样的改动.
