### ISSUE TITLE
Disable Sounds

### ISSUE THREAD

**Issue by focusedonfit** [Tangdixi/DCPathButton#16]
How can I disable the sounds? 
Thank you

**Comment by Tangdixi** [comment]
Well. Currently you can delete the audio files in **Sounds** to disable the sound. In next version I will add a property to handle this stuff :)

**Comment by focusedonfit** [comment]
Great thank you!

**Comment by wangweiarr** [comment]
这个做的还是非常不错的,对分享精神表示感谢. 不过提个建议,既然都加到pods上来了,为何不提高一下可制订性呢?比如中心按钮的旋转可控,声音或者是展开方向和展开半径还有扇区角度..  虽然有点麻烦,但还是希望能有这样的改动.

**Comment by Tangdixi** [comment]
Thanks for your advice and pull request :)  
I will update the pod spec later :+1:
