### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Amirnadi** [Tangdixi/DCPathButton#17]
I am using this control as described. but its not working. As fas as design concerns, its working but when i click on any buttonItem, it doesnot call its delegate. i am using btn.delegate = self. and adding the delegate and delegate actions as well.... plzzzz help me.

**Comment by Tangdixi** [comment]
Show me you code PLZ ~

**Comment by Amirnadi** [comment]
-(void)setUpMenu {
DCPathButton *btnSocialSharing = [[DCPathButton alloc]initWithCenterImage:[UIImage imageNamed:SOCIAL_SHARING_MENU]
                                                          hilightedImage:[UIImage imageNamed:SOCIAL_SHARING_MENU_HIGHLIGHT]];
    
    btnSocialSharing.delegate = self;
    DCPathItemButton *itemButton_1 = [[DCPathItemButton alloc]initWithImage:[UIImage
                                                                             imageNamed:SOCIAL_MESSAGES_IMAGE]
                                                           highlightedImage:[UIImage imageNamed:SOCIAL_MESSAGES_IMAGE]
                                                            backgroundImage:[UIImage imageNamed:@""]
                                                 backgroundHighlightedImage:[UIImage imageNamed:@""]];
    
    DCPathItemButton *itemButton_2 = [[DCPathItemButton alloc]initWithImage:[UIImage
                                                                             imageNamed:SOCIAL_TWITTER_IMAGE]
                                                           highlightedImage:[UIImage imageNamed:SOCIAL_TWITTER_IMAGE]
                                                            backgroundImage:[UIImage imageNamed:@""]
                                                 backgroundHighlightedImage:[UIImage imageNamed:@""]];
    
    
    DCPathItemButton *itemButton_3 = [[DCPathItemButton alloc]initWithImage:[UIImage
                                                                             imageNamed:SOCIAL_MAIL_IMAGE]
                                                           highlightedImage:[UIImage imageNamed:SOCIAL_MAIL_IMAGE]
                                                            backgroundImage:[UIImage imageNamed:@""]
                                                 backgroundHighlightedImage:[UIImage imageNamed:@""]];
    
    
    DCPathItemButton *itemButton_4 = [[DCPathItemButton alloc]initWithImage:[UIImage
                                                                             imageNamed:SOCIAL_WHATSAPP_IMAGE]
                                                           highlightedImage:[UIImage imageNamed:SOCIAL_WHATSAPP_IMAGE]
                                                            backgroundImage:[UIImage imageNamed:@""]
                                                 backgroundHighlightedImage:[UIImage imageNamed:@""]];
    
    
    DCPathItemButton *itemButton_5 = [[DCPathItemButton alloc]initWithImage:[UIImage
                                                                             imageNamed:SOCIAL_FACEBOOK_IMAGE]
                                                           highlightedImage:[UIImage imageNamed:SOCIAL_FACEBOOK_IMAGE]
                                                            backgroundImage:[UIImage imageNamed:@""]
                                                 backgroundHighlightedImage:[UIImage imageNamed:@""]];
    
    
    [btnSocialSharing addPathItems:@[itemButton_1, itemButton_2, itemButton_3, itemButton_4, itemButton_5]];
    
    btnSocialSharing.dcButtonCenter = CGPointMake(self.viewSocialSharingBack.bounds.size.width/2, self.viewSocialSharingBack.bounds.size.height/2);
 
    [self.viewSocialSharingBack addSubview:btnSocialSharing];
}


-(void)itemButtonTappedAtIndex:(NSUInteger)index {
    NSLog(@"------------->>>>");
}

**Comment by Amirnadi** [comment]
@Tangdixi sirr plzzz do update me with any issue.

**Comment by Tangdixi** [comment]
Hum... I see nothing wrong in your code. 
Let me think about it

**Comment by Tangdixi** [comment]
Can you give me a screen shot, I mean the **self.viewSocialSharingBack**

**Comment by Tangdixi** [comment]
According to your code, I think the reason to cause the item button failed is the superview's frame. Show me the **self.viewSocialSharingBack** and let's figure it out

**Comment by Amirnadi** [comment]
got ur point. I was setting a self.viewSocialSharingBack only at background of this button. Got the issue. Thanx :)

**Comment by Amirnadi** [comment]
ThankYou sir :)

**Comment by Tangdixi** [comment]
Cool ！
