### ISSUE TITLE
Issue using lib in Swift project - please help.

### ISSUE THREAD

**Issue by Vivanda** [Tangdixi/DCPathButton#19]
Hi there! Great work! However, I keep running into an issue when I use your lib in my swift project. I was hoping you can help?

__ERROR
/.../FoodStoryVC.swift:11:1: Type 'FStoryVC' does not conform to protocol 'DCPathButtonDelegate'

__ HEADER of my Swift file
import UIKit
class FStoryVC: UIViewController, UITableViewDelegate, UITextFieldDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate, UITextInputTraits, UIActionSheetDelegate, DCPathButtonDelegate { ...

__ IMPLEMENTATION
    // MARK: Delegate
    func itemButtonTappedAtIndex(index: Int)
    {
        println("You tap at index : \(index)")
    }
    
    override func preferredStatusBarStyle()->(UIStatusBarStyle)
    {
        return UIStatusBarStyle.LightContent
    }

    // MARK: Buttons
    func ConfigureDCPathButton() {
    
        // Configure center button
        //
        var dcPathButton: DCPathButton =  DCPathButton(centerImage: UIImage(named: "chooser-button-tab"), hilightedImage: UIImage(named: "hooser-button-tab-highlighted"))
        dcPathButton.delegate = self
        
        // Configure item buttons
        //
        var itemButton_1: DCPathItemButton = DCPathItemButton(image: UIImage(named: "chooser-moment-icon-music"), highlightedImage: UIImage(named: "chooser-moment-icon-music-highlighted"), backgroundImage: UIImage(named: "chooser-moment-button"), backgroundHighlightedImage: UIImage(named: "chooser-moment-button-highlighted"))
        
        var itemButton_2: DCPathItemButton = DCPathItemButton(image: UIImage(named: "chooser-moment-icon-place"), highlightedImage:  UIImage(named: "chooser-moment-icon-place-highlighted"), backgroundImage: UIImage(named: "chooser-moment-button"), backgroundHighlightedImage: UIImage(named: "chooser-moment-button-highlighted"))

        var itemButton_3: DCPathItemButton = DCPathItemButton(image: UIImage(named: "chooser-moment-icon-camera"), highlightedImage:  UIImage(named: "chooser-moment-icon-camera-highlighted"), backgroundImage: UIImage(named: "chooser-moment-button"), backgroundHighlightedImage: UIImage(named: "chooser-moment-button-highlighted"))

        var itemButton_4: DCPathItemButton = DCPathItemButton(image: UIImage(named: "chooser-moment-icon-thought"), highlightedImage:  UIImage(named: "chooser-moment-icon-thought-highlighted"), backgroundImage: UIImage(named: "chooser-moment-button"), backgroundHighlightedImage: UIImage(named: "chooser-moment-button-highlighted"))

        var itemButton_5: DCPathItemButton = DCPathItemButton(image: UIImage(named: "chooser-moment-icon-sleep"), highlightedImage:  UIImage(named: "chooser-moment-icon-sleep-highlighted"), backgroundImage: UIImage(named: "chooser-moment-button"), backgroundHighlightedImage: UIImage(named: "chooser-moment-button-highlighted"))

        // Add the item button into the center button
        //
        dcPathButton.addPathItems([itemButton_1, itemButton_2, itemButton_3, itemButton_4, itemButton_5])
        
        // Change the bloom radius
        dcPathButton.bloomRadius = 120.0
        
        // Change the DCButton's center
        dcPathButton.dcButtonCenter = CGPointMake(self.view.bounds.size.width / 2, self.view.bounds.size.height - 25.5)
        
        self.view.addSubview(dcPathButton)
        
    }

**Comment by Tangdixi** [comment]
Well, I think I have to update a **Swift** version

**Comment by Vivanda** [comment]
would you mind to take a look at it. I'm going crazy :) it can't be much but I cannot figure out what the issue is. thx!

**Comment by Vivanda** [comment]
Found the issue. For reference.

    func itemButtonTappedAtIndex(index: UInt) {
        println("You tap at index : \(index)")
    }
