### ISSUE TITLE
Disable sounds & ability to change them?

### ISSUE THREAD

**Issue by delannoyk** [Tangdixi/DCPathButton#20]
What do you think of letting user disabling sound if they'd like to and/or change the default sounds?

**Comment by Tangdixi** [comment]
Yep, you are right !  
Thanks @wangweiarr 's pull request.  
Now you can configure the sound or disable them :)  
I will update the **README** later

**Comment by delannoyk** [comment]
Oh ok then.

I didn't see @wangweiarr 's PR yesterday and I still don't see it so I forked anyway and made my changes (only to disable sounds right now). I suppose you don't want me to make the PR ? :)

**Comment by Tangdixi** [comment]
Here is @wangweiarr 's [PR](https://github.com/Tangdixi/DCPathButton/commit/64925cdc161ae79cd06a1052190a1446e5cd5a0e)  
But I found it just allow you to disable your sounds, not support to change them .   
And **PR** is welcome :) @delannoyk

**Comment by Tangdixi** [comment]
Sorry for the late reply.... 
Already add the feature about disable the sounds or change the sound ....
