### ISSUE TITLE
Button titles?

### ISSUE THREAD

**Issue by chrise86** [Tangdixi/DCPathButton#21]
Would it be possible to add titles above/below/around the buttons please? :)

**Comment by Tangdixi** [comment]
Thanks for your issue
But I think adding the title around the buttons may make the animations weird … 
If you really need these, maybe you can fork it and do some hack by yourself. Reply me if you need any help
:)

**Comment by chrise86** [comment]
I was thinking to fade in the labels after the animation stops, but there are no delegate methods or callbacks I don't think?

**Comment by Tangdixi** [comment]
Good idea，I think I can try

**Comment by Tangdixi** [comment]
Finally I give up this idea .... 
It doesn't look well ....
Maybe you can try some hack in my code .... 
Keep in touch if you need any help when you hacking my code ...
