### ISSUE TITLE
如何获取pathbutton被点击的事件,我在你的类里写了通知,但是会出bug,点击后不会消失

### ISSUE THREAD

**Issue by xiaosheng0601** [Tangdixi/DCPathButton#24]
如何获取pathbutton被点击的事件,我在你的类里写了通知,但是会出bug,点击后不会消失 点一下按钮就多一堆  点一下多一堆

**Comment by Tangdixi** [comment]
Please show me your code :)

**Comment by Tangdixi** [comment]
You don't need to use a notification. I already add some delegate methods. Try to use the **DCPathButtonDelegate**.  
 I will close this issue temporary
