### ISSUE TITLE
Regarding with commit d723afdcd

### ISSUE THREAD

**Issue by jiayuzhang** [Tangdixi/DCPathButton#25]
From d723afdcd32, the author does some enhancement on DCPathButton, however, all the working are done in Examples folder, could you fix it and update cocoapods accordingly?

**Comment by Tangdixi** [comment]
Sorry for the late reply.... 
I have already update the Pod to the newest version, aka v2.1 .... 
use `pod 'DCPathButton', '~> 2.1'` :)
