### ISSUE TITLE
TabbarControler + DCPathButton

### ISSUE THREAD

**Issue by JanRuettinger** [Tangdixi/DCPathButton#26]
Hello,

I try to integrate the DCPathButton into a tabbbar of a tabbarcontroller.
There is always something hidden (DCPathButton or tabbar).

I can do it with a viewvontroller and one extra tabbar, but then I have to copy the tabbar and all the segues to every involved view controller.  The code turns into chaos...

How could I fit that?

**Comment by Tangdixi** [comment]
You should add the **DCPathButton** into your TabBarController's view. Not the tabBar

**Comment by JanRuettinger** [comment]
1. I tried to put the DCPathButton into the view of TabBarController.
=> The Tabbar or the DCPathButton was hidden or not tabbar
2. I deleted the TabBarController and added a normal ViewController
=> There I added a TabBar by my own => it works fine, but really chaos

Your project is really amazing. I know that I do a mistake.
Could anyone upload a small demo project?

In your example project, you have also used a ViewController with an own implemented TabBar.
So that doesn't help me.

**Comment by Tangdixi** [comment]
PLZ give me your e-mail, I will send you a Demo.

**Comment by JanRuettinger** [comment]
Wrote you an e-mail!
Thanks a lot!

**Comment by Tangdixi** [comment]
AFK now ... Give you a [address](http://kuai.xunlei.com/d/GDxWAOYn7zxjVQQA471), it's full of Chinese, but I think you can find the download address. Leave a comment if you have any problems, reply U ASAP :)

**Comment by JanRuettinger** [comment]
Thanks works fine!

I have done the same….
Now everything is fine!
Thanks a lot and greets from Germany!

**Comment by Tangdixi** [comment]
No thanks～

**Comment by ruchiragile** [comment]
@Tangdixi, that link is broken. Would you please re-upload this demo? Thanks for this great component !!

**Comment by Tangdixi** [comment]
Forget the error link, I update the Example in the project, PLZ pull the repo

**Comment by ruchiragile** [comment]
Ok, thanks ! What about to have image and title for the button together?
