### ISSUE TITLE
Strange Error regarding the protocol

### ISSUE THREAD

**Issue by JanRuettinger** [Tangdixi/DCPathButton#27]
import UIKit

class TabController: UITabBarController, DCPathButtonDelegate{
    
    override func viewDidLoad() {
        super.viewDidLoad()
        configureDCButton()
        
        let testObject = PFObject(className: "TestObject")
        testObject["foo"] = "bar"
        testObject.saveInBackgroundWithBlock { (success: Bool, error: NSError?) -> Void in
            println("Object has been saved.")
        }

        // Do any additional setup after loading the view.
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    
    func configureDCButton() {
        
        // Configure center button
        //
        var dcPathButton: DCPathButton =  DCPathButton(centerImage: UIImage(named: "chooser-button-tab"), highlightedImage: UIImage(named: "chooser-button-tab-highlighted"))
        
        dcPathButton.delegate = self
        
        // Configure item buttons
        //
        
        var itemButton_0: DCPathItemButton = DCPathItemButton(image: UIImage(named: "drink"), highlightedImage:  UIImage(named: "drink"), backgroundImage: UIImage(named: "chooser-moment-button"), backgroundHighlightedImage: UIImage(named: "chooser-moment-button-highlighted"))
        
        var itemButton_1: DCPathItemButton = DCPathItemButton(image: UIImage(named: "food"), highlightedImage: UIImage(named: "food"), backgroundImage: UIImage(named: "chooser-moment-button"), backgroundHighlightedImage: UIImage(named: "chooser-moment-button-highlighted"))
        
        var itemButton_2: DCPathItemButton = DCPathItemButton(image: UIImage(named: "weight"), highlightedImage:  UIImage(named: "weight"), backgroundImage: UIImage(named: "chooser-moment-button"), backgroundHighlightedImage: UIImage(named: "chooser-moment-button-highlighted"))
        
        var itemButton_3: DCPathItemButton = DCPathItemButton(image: UIImage(named: "fitness"), highlightedImage:  UIImage(named: "fitness"), backgroundImage: UIImage(named: "chooser-moment-button"), backgroundHighlightedImage: UIImage(named: "chooser-moment-button-highlighted"))
        
        var itemButton_4: DCPathItemButton = DCPathItemButton(image: UIImage(named: "love"), highlightedImage:  UIImage(named: "love"), backgroundImage: UIImage(named: "chooser-moment-button"), backgroundHighlightedImage: UIImage(named: "chooser-moment-button-highlighted"))
        
        var itemButton_5: DCPathItemButton = DCPathItemButton(image: UIImage(named: "time"), highlightedImage:  UIImage(named: "time"), backgroundImage: UIImage(named: "chooser-moment-button"), backgroundHighlightedImage: UIImage(named: "chooser-moment-button-highlighted"))
        
        // Add the item button into the center button
        //
        dcPathButton.addPathItems([itemButton_0, itemButton_1, itemButton_2, itemButton_3, itemButton_4, itemButton_5])
        // Change the bloom radius
        dcPathButton.bloomRadius = 120.0
        // Change the DCButton's center
        dcPathButton.dcButtonCenter = CGPointMake(self.view.bounds.size.width / 2, self.view.bounds.size.height - 35.5)
        self.view.addSubview(dcPathButton)
    }
    
    func itemButtonTappedAtIndex(index: UInt) {
        println("You tap at index : \(index)")
    }
}

Error 1: Type 'TabController' does not conform to protocol 'DCPathButtonDelegat'
Error 2: dcPathButton.delegate = self => Cannot assign a value of type 'TabControler' to a value of type 'DCPathButtonDelegate!'

This is the method of the example project:
- (void)itemButtonTappedAtIndex:(NSUInteger)index
{
    NSLog(@"You tap at index : %zd", index);
}

How can I fix it?

**Comment by Tangdixi** [comment]
@JanRuettinger  
I have already add an example that using the **DCPathButton** in Swift.
