### ISSUE TITLE
Customize BottomView background color

### ISSUE THREAD

**Issue by ngheungyu** [Tangdixi/DCPathButton#28]
Thanks for this great plugin, this saved a lot of time to setup.

Could you add a property to customize the background color of the bottomView? I see the bottomview is a private property, i have no luck to change it.

Do you recommend 
1. simply move bottom view to public? or
2. support new property to customize background color of bottom view?

thanks.

**Comment by Tangdixi** [comment]
I add a property call `bottomViewColor. Use it to change the bottom color :)`

**Comment by ngheungyu** [comment]
Great!

**Comment by Tangdixi** [comment]
Wait a minute, pushing the change to the CocoaPods
