### ISSUE TITLE
Animated menu with image and title together

### ISSUE THREAD

**Issue by ruchiragile** [Tangdixi/DCPathButton#30]
Can you support button with images and text together? Currently its working good without text (title) but what if I want to show a title too. I dig into your code and have no luck to achieve this on my self. 

What you think?

**Comment by Tangdixi** [comment]
I try that before, it is weird ....  
If you really need a title. Just add the title as a subview when you init a `DCPathItemButton`.  
 And if you need the title appear after all the item button presented. Use  
`- (void)didPresentDCPathButtonItems:(DCPathButton *)dcPathButton`  

Maybe that is a solution

**Comment by ruchiragile** [comment]
Found that, `DCPathItemButton` takes size of image, we're assigning. I'm not sure how to add it as subview at proper place? I want o show an image at center and title below that image with same alignment.

Any ideas?

**Comment by Tangdixi** [comment]
Hmm ...  Maybe this:  
![screen shot 2015-06-30 at 5 30 29 pm](https://cloud.githubusercontent.com/assets/2090664/8427961/c5b9fd52-1f4d-11e5-92f6-7d508abd070b.png)

**Comment by Tangdixi** [comment]
1.  Get ready a rectangle image to init the `DCPathItemButton`.  
2.  Do something like this:  
```
DCPathItemButton *dcPathItemButton = /*Init Code*/  
UILabel *label = /*Init Code*/  
[dcPathItemButton addSubView:label]
/* Adjust label position code */  
/* Adjust the anchor point of dcPathItemButton */  
```

**Comment by ruchiragile** [comment]
Would you please upload a sample project showing this? Thanks a ton!

**Comment by Tangdixi** [comment]
I don't think so.  
Follow the steps in my previous comment. If you have any confusions. I will help U  
 I think you can make it.

**Comment by ruchiragile** [comment]
I've done it, thanks! :+1:

**Comment by Tangdixi** [comment]
Congratulations !

**Comment by Sindano92** [comment]
I'm still struggling to achieve this.
