### ISSUE TITLE
Example-Swift fails due to error in bridging header

### ISSUE THREAD

**Issue by mohonish** [Tangdixi/DCPathButton#31]
Example-Swift build fails with error `<unknown>:0: error: bridging header '/Users/Tangdixi/Desktop/Example-Swift/Example-Swift-Bridging-Header.h' does not exist`

I'm relatively new to swift and can't figure out what could be the problem.

**Comment by Tangdixi** [comment]
Sorry @mohonish, it's my fault  
T_T  
Already fix it~ PLZ `git pull` the change....

**Comment by Tangdixi** [comment]
Fixed

**Comment by mohonish** [comment]
Thanks! :+1:
