### ISSUE TITLE
How to increase touch area for DCPathButton?

### ISSUE THREAD

**Issue by hagile** [Tangdixi/DCPathButton#34]
How to increase touch area for DCPathButton?

See the below image

![screen shot 2015-09-09 at 2 52 46 pm](https://cloud.githubusercontent.com/assets/11436406/9758233/eade7a9e-5702-11e5-8a15-4e5839b7b375.png)

I'm able to implement DCPathButton in my app, thanks !! But I'm only able to show menu if my user taps on ( + ) button [see image]. Is there a way to increase touch area?

I tried, with this code that increase the area but I'm only able to touch ( + ) area.

**Comment by Tangdixi** [comment]
Sorry for the delayed respond, again ....  
I change some codes, now U can use 
```objc
- (instancetype)initWithButtonFrame:(CGRect)centerButtonFrame
                                     centerImage:(UIImage *)centerImage
                              highlightedImage:(UIImage *)centerHighlightedImage;
```

The podSpec is also updated. Use `pod 'DCPathButton', '~> 2.1.2'` instead

**Comment by Tangdixi** [comment]
Wait a minute .... 
The podSpec upload process has some problems .....

**Comment by hagile** [comment]
Update please?

**Comment by Tangdixi** [comment]
The podSpec has already updated.  :)

**Comment by hagile** [comment]
Can I use it with any other instance method? I'm using the one with only image,

    - (instancetype)initWithCenterImage:(UIImage *)centerImage
                   highlightedImage:(UIImage *)centerHighlightedImage;

**Comment by Tangdixi** [comment]
No, this method will init your touch area by the size of your image.

**Comment by Tangdixi** [comment]
Provide only one image is not a problems. Just focus on the `centerButtonFrame ` in 
```objc
- (instancetype)initWithButtonFrame:(CGRect)centerButtonFrame
                                     centerImage:(UIImage *)centerImage
                              highlightedImage:(UIImage *)centerHighlightedImage;
```  
method.

**Comment by hagile** [comment]
Alright ! Thanks, I’ll check and let you know.

**Comment by hagile** [comment]
Hi I'm not using CocoaPod.. How do I get it without Pod?

**Comment by Tangdixi** [comment]
See (cocoaPods)[www.cocoapods.org] and also U can directly clone the repo.

**Comment by Tangdixi** [comment]
@hagile Sorry for giving U a wrong website. See this (https://cocoapods.org)

**Comment by Tangdixi** [comment]
Issue close, reopen it if U got any problems @hagile
