### ISSUE TITLE
Hide Button when one item on tab has pushed

### ISSUE THREAD

**Issue by nucauthu** [Tangdixi/DCPathButton#36]
Could you help me the situation that one of tab in tabbar has pushed and hide the tabbar but the DCButton still there (because it added on the tabbar controller)? Do I have a solution that add the view into tabbar so when the tabbar hides, the dcbutton will hide?

Thanks in advance!

**Comment by Tangdixi** [comment]
Try this in the controller which U want to push your next controller and hide the **DCPathButton**:  

```objc
- (void)viewWillDisappear {
    _dcPathButton.hidden = YES;
}

- (void)viewWillAppear {
    _dcPathButton.hidden = NO;
}
```

**Comment by Tangdixi** [comment]
Meanwhile, U should make your **DCPathButton** become a public instance in your **TabBarController**.   
So the code maybe like this:  
```objc
- (void)viewWillDisappear {
    yourTabBarController.dcPathButton.hidden = YES;
}

- (void)viewWillAppear {
    yourTabBarController.dcPathButton.hidden = NO;
}
```

**Comment by nucauthu** [comment]
Thanks. However, something strange happens when I show it back. It didn't appear. I have debug and see that the UITarbar is not in the TabbarController subviews when viewWillAppear call (even viewDisappear). So when I make the dcPathButton on, then the UITabbar add to subviews, the UITabbar will overlap the dcPathButton. I solved this with bringing it to top of views after delay 0.2s.

Please fill me if I have lacked some knowledge. My solution isn't really good and I'm not really like it :(

**Comment by Tangdixi** [comment]
My solution should have no problems.    
How do U create your tabBarViewController?  Show me more detail.

**Comment by Tangdixi** [comment]
Issue close ~
