### ISSUE TITLE
Background shading does not appear in Swift / IOS9 / Xcode 7 example

### ISSUE THREAD

**Issue by mikesparr** [Tangdixi/DCPathButton#40]
I launch in Xcode 7.0.1 with IOS9 on latest OSX (El Capitan) and simulator for iPhone 6s. Portrait works fine but all other orientations the button disappears as noted in #39 and when tapping on button, the background does not shade.

![simulator screen shot oct 19 2015 8 39 42 pm](https://cloud.githubusercontent.com/assets/5553105/10596462/cbb215f4-76a1-11e5-9dd6-74a4989a6ffc.png)

**Comment by Tangdixi** [comment]
Move this issue to https://github.com/Tangdixi/DCPathButton/issues/39
