### ISSUE TITLE
Disable Rotation of Icons 

### ISSUE THREAD

**Issue by glentregoning** [Tangdixi/DCPathButton#41]
I've found the rotation of the icons a little distracting on tap. 

I was wondering if you could add a configuration option to disable rotation.

**Comment by Tangdixi** [comment]
Add a property call **allowSubItemRotation**

**Comment by glentregoning** [comment]
allowSubItemRotation doesn't appear to be implemented in 2.1.3

**Comment by Tangdixi** [comment]
wait a second

**Comment by Tangdixi** [comment]
@glentregoning 
 Something wrong when I commit the changes.  Now everything is fine.

**Comment by Tangdixi** [comment]
If everything is fine, close this issue. @glentregoning

**Comment by glentregoning** [comment]
When I set allowSubItemRotation to false I still see my menu items rotate. I was thinking this should block that?

**Comment by Tangdixi** [comment]
Sorry.....  
I forgot to update the git tag... So it always use the old tag
T_T

**Comment by Tangdixi** [comment]
@glentregoning Now it should works, right?

**Comment by glentregoning** [comment]
yep works now thanks
