### ISSUE TITLE
Add documentation for bottomViewColor.

### ISSUE THREAD

**Issue by ianhirschfeld** [Tangdixi/DCPathButton#45]
Saw in your example you have `DCPathButton.bottomViewColor` exposed as something that can bet set.

**Comment by Tangdixi** [comment]
Well, that's my fault. I put this property in a wrong place.  
But I think maybe you need this property?  
Already fixed it.  
:)

**Comment by ianhirschfeld** [comment]
Ahh I see, haha yes I like that you can set it! :grin:
