### ISSUE TITLE
Delegate Improvements

### ISSUE THREAD

**Issue by Incyc** [Tangdixi/DCPathButton#46]
The delegates `willDismissDCPathButtonItems:` and `didDismissDCPathButtonItems:` are not fired unless you tap on the center button to dismiss. I would think they also get fired when tapping on one of the button items.

Currently there is no way to trigger an action after the dismiss animation, because `pathButton:clickItemButtonAtIndex:` happens on tap.

As an improvement, I suggest either:
1. All 3 of these delegates should fire in the right sequence.
2. Add a new delegate to fire after the dismiss animation for selecting an item button index.

**Comment by Tangdixi** [comment]
Fixed.  
PLZ reinstall through PodSpec
