### ISSUE TITLE
点击+号按钮“开屏”后，再点击背景可能无法收回来

### ISSUE THREAD

**Issue by LCcccccc** [Tangdixi/DCPathButton#51]
1. 在模拟器上，开屏后再点击第一个TabBarItem靠左侧区域变暗背景，收不回来，iOS8,9都会出现该现象
2. 并且在我的6s真机上测试，开屏后，点击+号左侧任意的TabBarItem都必定无法收回DCPathButtonItems，而点击左侧的空白背景区域则有一定概率收不回。

以上是我的粗略测试。

**Comment by Tangdixi** [comment]
Fixing

**Comment by Tangdixi** [comment]
Fixed

**Comment by LCcccccc** [comment]
Thank you!
