### ISSUE TITLE
Wrong frame with iOS8 Auto layout

### ISSUE THREAD

**Issue by dulgan** [Tangdixi/DCPathButton#6]
Hi,
I'm trying to use this control in my app but I'm facin some issues :+1: 
1) I tried to put the button in my view controller above a mapView, positioned with autolayout constraints 
Result : the button is not clickable

2) I tried to put the button in a view above the mapView, I appear to be a the right place if I set it's frame to, say CGRectMake(0,0,35,35).
Result : the button is clickable but once expanded, the items are not clickable. Moreover the button goes far away from it's superview  just after selecting the center button to cancel action.

Do you have any clue on how to use it properly in a storyboard app using auto layout ?

Thanks for your work anyway.

**Comment by kalyan4** [comment]
My task is to change tabbar iem position change according to user criteria my if-condition not perfectly working at this point
CGPoint touchlocation;
[pan locationInView:self.view];

if (tabbarview == nil) {
    tabbarview =[tbItems objectAtIndex:self.tabBarController.selectedIndex];
    [self.tabBarController.view addSubview:tabbarview];
}
if (fixedPos == 0) {
    fixedPos=touchlocation.y;

}[tabbarview removeFromSuperview];
tabbarview.center = touchlocation;

if (pan.state == UIGestureRecognizerStateEnded) {
    // [tabbarview removefromsuperview]
    [tabbarview removeFromSuperview];
    tabbarview =nil;
    fixedPos = 0;

    if(touchlocation.x<4){

        if (touchlocation.x<=109)
        {
            [tbItems exchangeObjectAtIndex:0 withObjectAtIndex:self.tabBarController.selectedIndex];
            NSMutableArray *tvcs=[[self.tabBarController viewControllers]mutableCopy];
            id tempvc=[tvcs objectAtIndex:self.tabBarController.selectedIndex];
            [tvcs removeObject:tempvc];
            [tvcs insertObject:tempvc atIndex:1];
            [self.tabBarController setViewControllers:tvcs animated:YES];

        }else
        if (touchlocation.x>109 && touchlocation.x<=215)
        {
            [tbItems exchangeObjectAtIndex:1 withObjectAtIndex:self.tabBarController.selectedIndex];
            NSMutableArray *tvcs=[[self.tabBarController viewControllers]mutableCopy];
            id tempvc=[tvcs objectAtIndex:self.tabBarController.selectedIndex];
            [tvcs removeObject:tempvc];
            [tvcs insertObject:tempvc atIndex:2];
            [self.tabBarController setViewControllers:tvcs animated:YES];

        }else if (touchlocation.x>215 )
        {
            [tbItems exchangeObjectAtIndex:2 withObjectAtIndex:self.tabBarController.selectedIndex];
            NSMutableArray *tvcs=[[self.tabBarController viewControllers]mutableCopy];
            id tempvc=[tvcs objectAtIndex:self.tabBarController.selectedIndex];
            [tvcs removeObject:tempvc];
            [tvcs insertObject:tempvc atIndex:3];
            [self.tabBarController setViewControllers:tvcs animated:YES];

        }else
        {
            [tbItems exchangeObjectAtIndex:3 withObjectAtIndex:4];
            NSMutableArray *tvcs=[[self.tabBarController viewControllers]mutableCopy];
            id tempvc=[tvcs objectAtIndex:self.tabBarController.selectedIndex];
            [tvcs removeObject:tempvc];
            [tvcs insertObject:tempvc atIndex:4];
            [self.tabBarController setViewControllers:tvcs animated:YES];
        }


    }else
    {
        [tbItems exchangeObjectAtIndex:3 withObjectAtIndex:4];
        NSMutableArray *tvcs=[[self.tabBarController viewControllers]mutableCopy];
        id tempvc=[tvcs objectAtIndex:self.tabBarController.selectedIndex];
        [tvcs removeObject:tempvc];
        [tvcs insertObject:tempvc atIndex:4];
        [self.tabBarController setViewControllers:tvcs animated:YES];
    }
}
